
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.operator.com
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.operator.com
  resources:
  - nodepools/finalizers
  verbs:
  - update
- apiGroups:
  - apps.operator.com
  resources:
  - nodepools/status
  verbs:
  - get
  - patch
  - update
