apiVersion: apps.operator.com/v1
kind: Nodepool
metadata:
  name: master
spec:
  # Add fields here
  taints: 
    - key: node-pool.test
      value: master
      effect: NoSchedule
  labels:
    "node-pool.lailin.xyz/master": "8"
  ncl: runc
